// DO NOT EDIT
// Generated by JFlex 1.8.1 http://jflex.de/
// source: shrug.flex

package com.shrug.Parser;

import java.io.*;
import com.shrug.AST.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u1f00"+
    "\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u1f00\1\u4d00\1\u4e00\1\u4f00"+
    "\1\u5000\3\u0100\1\u5100\1\u5200\1\u5300\12\u1f00\4\u0100\1\u5400"+
    "\17\u1f00\2\u0100\1\u5500\41\u1f00\2\u0100\1\u5600\1\u5700\2\u1f00"+
    "\1\u5800\1\u5900\27\u0100\1\u5a00\2\u0100\1\u5b00\45\u1f00\1\u0100"+
    "\1\u5c00\1\u5d00\11\u1f00\1\u5e00\24\u1f00\1\u5f00\1\u6000\1\u1f00"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\2\u1f00\1\u6500\5\u1f00\1\u6600"+
    "\1\u6700\1\u6800\5\u1f00\1\u6900\1\u6a00\2\u1f00\1\u6b00\1\u1f00"+
    "\1\u6c00\21\u1f00\246\u0100\1\u6d00\20\u0100\1\u6e00\1\u6f00\25\u0100"+
    "\1\u7000\34\u0100\1\u7100\14\u1f00\2\u0100\1\u7200\u0b05\u1f00\1\u7300"+
    "\1\u7400\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\16\0\10\1\1\2\2\1\1\3\1\4"+
    "\1\5\2\1\1\6\3\1\12\0\7\1\32\2\4\1"+
    "\1\2\1\1\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\2\2\1\20\1\2\1\21\1\22"+
    "\2\2\1\23\1\24\1\25\1\26\5\2\4\1\41\0"+
    "\2\1\4\2\4\1\1\2\2\1\1\0\7\1\1\2"+
    "\4\1\1\2\5\1\27\2\1\1\37\2\1\1\u01ca\2"+
    "\4\1\14\2\16\1\5\2\7\1\1\2\1\1\1\2"+
    "\21\1\160\0\5\2\1\1\2\2\2\1\4\2\1\1"+
    "\1\2\6\1\1\2\1\1\3\2\1\1\1\2\1\1"+
    "\24\2\1\1\123\2\1\1\213\2\1\1\5\0\2\1"+
    "\246\2\1\1\46\2\2\1\1\2\6\1\51\2\6\1"+
    "\1\2\1\1\55\0\1\1\1\0\1\1\2\0\1\1"+
    "\2\0\1\1\1\0\10\1\33\2\4\1\4\2\15\1"+
    "\6\0\5\1\1\2\4\1\13\0\1\1\1\0\3\1"+
    "\53\2\37\0\4\1\2\2\1\0\143\2\1\1\1\2"+
    "\10\0\1\1\6\0\2\2\2\0\1\1\4\0\2\2"+
    "\12\0\3\2\2\1\1\2\17\1\1\0\1\2\1\0"+
    "\36\2\33\0\2\1\131\2\13\0\1\2\16\1\12\0"+
    "\41\2\11\0\2\2\4\1\1\2\2\1\1\0\30\2"+
    "\4\0\1\2\11\0\1\2\3\0\1\2\5\0\22\1"+
    "\31\2\3\0\4\1\13\2\65\1\25\2\1\1\10\2"+
    "\25\1\61\0\66\2\3\0\1\2\22\0\1\2\7\0"+
    "\12\2\2\0\2\1\12\0\1\1\20\2\3\0\1\1"+
    "\10\2\2\1\2\2\2\1\26\2\1\1\7\2\1\1"+
    "\1\2\3\1\4\2\2\1\1\0\1\2\7\0\2\1"+
    "\2\0\2\1\3\0\1\2\10\1\1\0\4\1\2\2"+
    "\1\1\3\2\2\0\2\1\12\0\4\2\7\1\2\2"+
    "\1\1\1\0\2\1\3\0\1\1\6\2\4\1\2\2"+
    "\2\1\26\2\1\1\7\2\1\1\2\2\1\1\2\2"+
    "\1\1\2\2\2\1\1\0\1\1\5\0\4\1\2\0"+
    "\2\1\3\0\3\1\1\0\7\1\4\2\1\1\1\2"+
    "\7\1\14\0\3\2\1\0\13\1\3\0\1\1\11\2"+
    "\1\1\3\2\1\1\26\2\1\1\7\2\1\1\2\2"+
    "\1\1\5\2\2\1\1\0\1\2\10\0\1\1\3\0"+
    "\1\1\3\0\2\1\1\2\17\1\2\2\2\0\2\1"+
    "\12\0\1\1\1\2\7\1\1\2\6\0\1\1\3\0"+
    "\1\1\10\2\2\1\2\2\2\1\26\2\1\1\7\2"+
    "\1\1\2\2\1\1\5\2\2\1\1\0\1\2\7\0"+
    "\2\1\2\0\2\1\3\0\10\1\2\0\4\1\2\2"+
    "\1\1\3\2\2\0\2\1\12\0\1\1\1\2\20\1"+
    "\1\0\1\2\1\1\6\2\3\1\3\2\1\1\4\2"+
    "\3\1\2\2\1\1\1\2\1\1\2\2\3\1\2\2"+
    "\3\1\3\2\3\1\14\2\4\1\5\0\3\1\3\0"+
    "\1\1\4\0\2\1\1\2\6\1\1\0\16\1\12\0"+
    "\11\1\1\2\6\1\5\0\10\2\1\1\3\2\1\1"+
    "\27\2\1\1\20\2\3\1\1\2\7\0\1\1\3\0"+
    "\1\1\4\0\7\1\2\0\1\1\3\2\5\1\2\2"+
    "\2\0\2\1\12\0\20\1\1\2\3\0\1\1\10\2"+
    "\1\1\3\2\1\1\27\2\1\1\12\2\1\1\5\2"+
    "\2\1\1\0\1\2\7\0\1\1\3\0\1\1\4\0"+
    "\7\1\2\0\7\1\1\2\1\1\2\2\2\0\2\1"+
    "\12\0\1\1\2\2\15\1\4\0\1\1\10\2\1\1"+
    "\3\2\1\1\51\2\2\0\1\2\7\0\1\1\3\0"+
    "\1\1\4\0\1\2\5\1\3\2\1\0\7\1\3\2"+
    "\2\0\2\1\12\0\12\1\6\2\2\1\2\0\1\1"+
    "\22\2\3\1\30\2\1\1\11\2\1\1\1\2\2\1"+
    "\7\2\3\1\1\0\4\1\6\0\1\1\1\0\1\1"+
    "\10\0\6\1\12\0\2\1\2\0\15\1\60\2\1\0"+
    "\2\2\7\0\4\1\10\2\10\0\1\1\12\0\47\1"+
    "\2\2\1\1\1\2\1\1\5\2\1\1\30\2\1\1"+
    "\1\2\1\1\12\2\1\0\2\2\11\0\1\2\2\1"+
    "\5\2\1\1\1\2\1\1\6\0\2\1\12\0\2\1"+
    "\4\2\40\1\1\2\27\1\2\0\6\1\12\0\13\1"+
    "\1\0\1\1\1\0\1\1\1\0\4\1\2\0\10\2"+
    "\1\1\44\2\4\1\24\0\1\1\2\0\5\2\13\0"+
    "\1\1\44\0\11\1\1\0\71\1\53\2\24\0\1\2"+
    "\12\0\6\1\6\2\4\0\4\2\3\0\1\2\3\0"+
    "\2\2\7\0\3\2\4\0\15\2\14\0\1\2\17\0"+
    "\2\1\46\2\1\1\1\2\5\1\1\2\2\1\53\2"+
    "\1\1\115\2\1\1\4\2\2\1\7\2\1\1\1\2"+
    "\1\1\4\2\2\1\51\2\1\1\4\2\2\1\41\2"+
    "\1\1\4\2\2\1\7\2\1\1\1\2\1\1\4\2"+
    "\2\1\17\2\1\1\71\2\1\1\4\2\2\1\103\2"+
    "\2\1\3\0\40\1\20\2\20\1\126\2\2\1\6\2"+
    "\3\1\u016c\2\2\1\21\2\1\1\32\2\5\1\113\2"+
    "\3\1\13\2\7\1\15\2\1\1\4\2\3\0\13\1"+
    "\22\2\3\0\13\1\22\2\2\0\14\1\15\2\1\1"+
    "\3\2\1\1\2\0\14\1\64\2\40\0\3\1\1\2"+
    "\3\1\2\2\1\0\2\1\12\0\41\1\4\0\1\1"+
    "\12\0\6\1\131\2\7\1\5\2\2\0\42\2\1\0"+
    "\1\2\5\1\106\2\12\1\37\2\1\1\14\0\4\1"+
    "\14\0\12\1\12\0\36\2\2\1\5\2\13\1\54\2"+
    "\4\1\32\2\6\1\12\0\46\1\27\2\5\0\4\1"+
    "\65\2\12\0\1\1\35\0\2\1\13\0\6\1\12\0"+
    "\15\1\1\2\10\1\16\0\102\1\5\0\57\2\21\0"+
    "\7\2\4\1\12\0\21\1\11\0\14\1\3\0\36\2"+
    "\15\0\2\2\12\0\54\2\16\0\14\1\44\2\24\0"+
    "\10\1\12\0\3\1\3\2\12\0\44\2\2\1\11\2"+
    "\7\1\53\2\2\1\3\2\20\1\3\0\1\1\25\0"+
    "\4\2\1\0\6\2\1\0\2\2\3\0\1\2\5\1"+
    "\300\2\72\0\1\1\5\0\26\2\2\1\6\2\2\1"+
    "\46\2\2\1\6\2\2\1\10\2\1\1\1\2\1\1"+
    "\1\2\1\1\1\2\1\1\37\2\2\1\65\2\1\1"+
    "\7\2\1\1\1\2\3\1\3\2\1\1\7\2\3\1"+
    "\4\2\2\1\6\2\4\1\15\2\5\1\3\2\1\1"+
    "\7\2\16\1\5\0\32\1\5\0\20\1\2\2\23\1"+
    "\1\2\13\1\5\0\1\1\12\0\1\1\1\2\15\1"+
    "\1\2\20\1\15\2\3\1\40\2\20\1\15\0\4\1"+
    "\1\0\3\1\14\0\21\1\1\2\4\1\1\2\2\1"+
    "\12\2\1\1\1\2\3\1\5\2\6\1\1\2\1\1"+
    "\1\2\1\1\1\2\1\1\4\2\1\1\13\2\2\1"+
    "\4\2\5\1\5\2\4\1\1\2\21\1\51\2\u0177\1"+
    "\57\2\1\1\57\2\1\1\205\2\6\1\4\2\3\0"+
    "\2\2\14\1\46\2\1\1\1\2\5\1\1\2\2\1"+
    "\70\2\7\1\1\2\17\1\1\0\27\2\11\1\7\2"+
    "\1\1\7\2\1\1\7\2\1\1\7\2\1\1\7\2"+
    "\1\1\7\2\1\1\7\2\1\1\7\2\1\1\40\0"+
    "\57\1\1\2\325\1\3\2\31\1\11\2\6\0\1\1"+
    "\5\2\2\1\5\2\4\1\126\2\2\1\2\0\2\1"+
    "\3\2\1\1\132\2\1\1\4\2\5\1\53\2\1\1"+
    "\136\2\21\1\33\2\65\1\306\2\112\1\360\2\20\1"+
    "\215\2\103\1\56\2\2\1\15\2\3\1\20\2\12\0"+
    "\2\2\24\1\57\2\1\0\4\1\12\0\1\1\37\2"+
    "\2\0\120\2\2\0\45\1\11\2\2\1\147\2\2\1"+
    "\65\2\2\1\5\2\60\1\13\2\1\0\3\2\1\0"+
    "\4\2\1\0\27\2\5\0\20\1\1\2\7\1\64\2"+
    "\14\1\2\0\62\2\22\0\12\1\12\0\6\1\22\0"+
    "\6\2\3\1\1\2\1\1\2\2\13\0\34\2\10\0"+
    "\2\1\27\2\15\0\14\1\35\2\3\1\4\0\57\2"+
    "\16\0\16\1\1\2\12\0\6\1\5\2\1\0\12\2"+
    "\12\0\5\2\1\1\51\2\16\0\11\1\3\2\1\0"+
    "\10\2\2\0\2\1\12\0\6\1\27\2\3\1\1\2"+
    "\3\0\62\2\1\0\1\2\3\0\2\2\2\0\5\2"+
    "\2\0\1\2\1\0\1\2\30\1\3\2\2\1\13\2"+
    "\5\0\2\1\3\2\2\0\12\1\6\2\2\1\6\2"+
    "\2\1\6\2\11\1\7\2\1\1\7\2\1\1\53\2"+
    "\1\1\14\2\10\1\163\2\10\0\1\1\2\0\2\1"+
    "\12\0\6\1\244\2\14\1\27\2\4\1\61\2\4\1"+
    "\156\2\2\1\152\2\46\1\7\2\14\1\5\2\5\1"+
    "\1\2\1\0\12\2\1\1\15\2\1\1\5\2\1\1"+
    "\1\2\1\1\2\2\1\1\2\2\1\1\154\2\41\1"+
    "\153\2\22\1\100\2\2\1\66\2\50\1\15\2\3\1"+
    "\20\0\20\1\20\0\3\1\2\2\30\1\3\2\31\1"+
    "\1\2\6\1\5\2\1\1\207\2\2\1\1\0\4\1"+
    "\1\2\13\1\12\0\7\1\32\2\4\1\1\2\1\1"+
    "\32\2\13\1\131\2\3\1\6\2\2\1\6\2\2\1"+
    "\6\2\2\1\3\2\3\1\2\2\3\1\2\2\22\1"+
    "\3\0\4\1\14\2\1\1\32\2\1\1\23\2\1\1"+
    "\2\2\1\1\17\2\2\1\16\2\42\1\173\2\105\1"+
    "\65\2\210\1\1\0\202\1\35\2\3\1\61\2\17\1"+
    "\1\0\37\1\40\2\15\1\36\2\5\1\46\2\5\0"+
    "\5\1\36\2\2\1\44\2\4\1\10\2\1\1\5\2"+
    "\52\1\236\2\2\1\12\0\6\1\44\2\4\1\44\2"+
    "\4\1\50\2\10\1\64\2\234\1\67\2\11\1\26\2"+
    "\12\1\10\2\230\1\6\2\2\1\1\2\1\1\54\2"+
    "\1\1\2\2\3\1\1\2\2\1\27\2\12\1\27\2"+
    "\11\1\37\2\101\1\23\2\1\1\2\2\12\1\26\2"+
    "\12\1\32\2\106\1\70\2\6\1\2\2\100\1\1\2"+
    "\3\0\1\1\2\0\5\1\4\0\4\2\1\1\3\2"+
    "\1\1\35\2\2\1\3\0\4\1\1\0\40\1\35\2"+
    "\3\1\35\2\43\1\10\2\1\1\34\2\2\0\31\1"+
    "\66\2\12\1\26\2\12\1\23\2\15\1\22\2\156\1"+
    "\111\2\67\1\63\2\15\1\63\2\15\1\44\2\4\0"+
    "\10\1\12\0\306\1\35\2\12\1\1\2\10\1\26\2"+
    "\13\0\217\1\27\2\11\1\3\0\65\2\17\0\37\1"+
    "\12\0\17\1\4\0\55\2\13\0\2\1\1\0\17\1"+
    "\1\0\2\1\31\2\7\1\12\0\6\1\3\0\44\2"+
    "\16\0\1\1\12\0\4\1\1\2\2\0\11\1\43\2"+
    "\1\0\2\1\1\2\11\1\3\0\60\2\16\0\4\2"+
    "\4\1\4\0\3\1\12\0\1\2\1\1\1\2\43\1"+
    "\22\2\1\1\31\2\14\0\6\1\1\0\101\1\7\2"+
    "\1\1\1\2\1\1\4\2\1\1\17\2\1\1\12\2"+
    "\7\1\57\2\14\0\5\1\12\0\6\1\4\0\1\1"+
    "\10\2\2\1\2\2\2\1\26\2\1\1\7\2\1\1"+
    "\2\2\1\1\5\2\1\1\2\0\1\2\7\0\2\1"+
    "\2\0\2\1\3\0\2\1\1\2\6\1\1\0\5\1"+
    "\5\2\2\0\2\1\7\0\3\1\5\0\213\1\65\2"+
    "\22\0\4\2\5\1\12\0\4\1\1\0\1\2\40\1"+
    "\60\2\24\0\2\2\1\1\1\2\10\1\12\0\246\1"+
    "\57\2\7\0\2\1\11\0\27\1\4\2\2\0\42\1"+
    "\60\2\21\0\3\1\1\2\13\1\12\0\46\1\53\2"+
    "\15\0\1\2\7\1\12\0\66\1\33\2\2\1\17\0"+
    "\4\1\12\0\306\1\54\2\17\0\145\1\100\2\12\0"+
    "\25\1\1\2\240\1\10\2\2\1\47\2\7\0\2\1"+
    "\7\0\1\2\1\1\1\2\1\0\33\1\1\2\12\0"+
    "\50\2\7\0\1\2\4\0\10\1\1\0\10\1\1\2"+
    "\13\0\56\2\20\0\3\1\1\2\42\1\71\2\7\1"+
    "\11\2\1\1\45\2\10\0\1\1\10\0\1\2\17\1"+
    "\12\0\30\1\36\2\2\1\26\0\1\1\16\0\111\1"+
    "\7\2\1\1\2\2\1\1\46\2\6\0\3\1\1\0"+
    "\1\1\2\0\1\1\7\0\1\2\1\0\10\1\12\0"+
    "\6\1\6\2\1\1\2\2\1\1\40\2\5\0\1\1"+
    "\2\0\1\1\5\0\1\2\7\1\12\0\u0136\1\23\2"+
    "\4\0\346\1\4\2\37\1\232\2\146\1\157\2\21\1"+
    "\304\2\274\1\57\2\1\1\11\0\307\1\107\2\271\1"+
    "\71\2\7\1\37\2\1\1\12\0\146\1\36\2\2\1"+
    "\5\0\13\1\60\2\7\0\11\1\4\2\14\1\12\0"+
    "\11\1\25\2\5\1\23\2\260\1\100\2\200\1\113\2"+
    "\4\1\1\0\1\2\67\0\7\1\4\0\15\2\100\1"+
    "\2\2\1\1\1\2\34\1\370\2\10\1\363\2\15\1"+
    "\37\2\61\1\3\2\21\1\4\2\10\1\u018c\2\4\1"+
    "\153\2\5\1\15\2\3\1\11\2\7\1\12\2\3\1"+
    "\2\0\1\1\4\0\301\1\5\0\3\1\26\0\2\1"+
    "\7\0\36\1\4\0\224\1\3\0\273\1\125\2\1\1"+
    "\107\2\1\1\2\2\2\1\1\2\2\1\2\2\2\1"+
    "\4\2\1\1\14\2\1\1\1\2\1\1\7\2\1\1"+
    "\101\2\1\1\4\2\2\1\10\2\1\1\7\2\1\1"+
    "\34\2\1\1\4\2\1\1\5\2\1\1\1\2\3\1"+
    "\7\2\1\1\u0154\2\2\1\31\2\1\1\31\2\1\1"+
    "\37\2\1\1\31\2\1\1\37\2\1\1\31\2\1\1"+
    "\37\2\1\1\31\2\1\1\37\2\1\1\31\2\1\1"+
    "\10\2\2\1\151\0\4\1\62\0\10\1\1\0\16\1"+
    "\1\0\26\1\5\0\1\1\17\0\120\1\7\0\1\1"+
    "\21\0\2\1\7\0\1\1\2\0\1\1\5\0\325\1"+
    "\55\2\3\1\7\0\7\2\2\1\12\0\4\1\1\2"+
    "\u0171\1\54\2\16\0\5\1\306\2\13\1\7\0\51\1"+
    "\104\2\7\0\1\2\4\1\12\0\u0156\1\1\2\117\1"+
    "\4\2\1\1\33\2\1\1\2\2\1\1\1\2\2\1"+
    "\1\2\1\1\12\2\1\1\4\2\1\1\1\2\1\1"+
    "\1\2\6\1\1\2\4\1\1\2\1\1\1\2\1\1"+
    "\1\2\1\1\3\2\1\1\2\2\1\1\1\2\2\1"+
    "\1\2\1\1\1\2\1\1\1\2\1\1\1\2\1\1"+
    "\1\2\1\1\2\2\1\1\1\2\2\1\4\2\1\1"+
    "\7\2\1\1\4\2\1\1\4\2\1\1\1\2\1\1"+
    "\12\2\1\1\21\2\5\1\3\2\1\1\5\2\1\1"+
    "\21\2\104\1\327\2\51\1\65\2\13\1\336\2\2\1"+
    "\u0182\2\16\1\u0131\2\37\1\36\2\343\1\1\0\36\1"+
    "\140\0\200\1\360\0\20\1";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29952];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\26\0"+
    "\1\6\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[31];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\27\0\56\0\105\0\27\0\27\0\27\0\134"+
    "\0\163\0\212\0\241\0\270\0\317\0\346\0\375\0\u0114"+
    "\0\u012b\0\u0142\0\u0159\0\u0170\0\u0187\0\u019e\0\u01b5\0\u01cc"+
    "\0\u01e3\0\u01fa\0\u0211\0\u0228\0\u023f\0\27\0\u0256";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[31];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\5\1\6\1\7\20\3\27\0"+
    "\1\3\1\0\1\3\4\0\20\3\10\0\1\10\1\11"+
    "\1\12\1\0\1\13\2\0\1\14\1\15\3\0\1\16"+
    "\24\0\1\17\22\0\1\20\32\0\1\21\24\0\1\22"+
    "\27\0\1\23\27\0\1\24\22\0\1\25\32\0\1\26"+
    "\13\0\1\27\45\0\1\30\22\0\1\31\31\0\1\32"+
    "\22\0\1\33\27\0\1\34\24\0\1\32\31\0\1\32"+
    "\13\0\1\35\25\0\1\23\22\0\1\36\40\0\1\32"+
    "\34\0\1\23\23\0\1\37\21\0\1\32\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[621];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\3\11\26\0\1\11\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[31];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Node yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <" + yytext()+">");
            }
            // fall through
          case 7: break;
          case 2:
            { return new IDNode (yytext());
            }
            // fall through
          case 8: break;
          case 3:
            { return new LParenNode();
            }
            // fall through
          case 9: break;
          case 4:
            { return new RParenNode();
            }
            // fall through
          case 10: break;
          case 5:
            { return new CommaNode();
            }
            // fall through
          case 11: break;
          case 6:
            { return new PrimitiveTypeNode (yytext());
            }
            // fall through
          case 12: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
